language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.5
otp_release:
  - 18.3
  - 19.3
  - 20.3
sudo: false # to use faster container based build environment
script:
  - mix deps.get
  - mix espec
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
